name: Publish

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10.27.0"

      - name: Install wrangler
        run: pnpm install

      - name: Build site
        run: python ./generator/main.py

      - name: Deploy to Cloudflare Pages
        run: pnpm wrangler pages deploy build --project-name ${{ vars.CLOUDFLARE_PROJECT_NAME }}
        env:
          CLOUDFLARE_ACCESS_CLIENT_ID: ${{ secrets.CLOUDFLARE_ACCESS_CLIENT_ID }}
          CLOUDFLARE_ACCESS_CLIENT_SECRET: ${{ secrets.CLOUDFLARE_ACCESS_CLIENT_SECRET }}
